cors:
  originPatterns: http://localhost:3000,http://localhost:8080,http://localhost:5173
file:
    upload-dir: /home/ninho/Documents/projetos_pessoal/trip-plans/uploadDir
spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trip_plans?useTimezone=true&serverTimezone=UTC
    username: root
    password: mullen2906

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request=-size: 215MB
      file-size-threshold: 2KB
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
